apiVersion: apps/v1
kind: Deployment

metadata:
  name: chat

spec:
  replicas: 3

  selector:
    matchLabels:
      app: chat

  template:
    metadata:
      labels:
        app: chat

    spec:
      containers:
        - name: chat
          image: ghcr.io/saeidel-saadi/chat-room:326737c999e8bcc20123f229a881c7c50f0162ef
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10